version: "3.8"
services:
  dev-postgres:
    image: postgres:15.1-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ticket
    restart: always
    networks:
      - dev
networks:
  dev:
